name: weather_task_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  injectable: ^1.5.3
  pretty_dio_logger: ^1.1.1




dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  freezed_annotation: ^2.0.3
  injectable_generator:
  json_serializable: ^6.2.0



flutter:
  uses-material-design: true

